language: generic
sudo: required

# Is used to install docker
services:
  - docker

# Tells Travis CI to the docker command
before_install:
  - docker build  -t aricahrdson87/frontend -f Dockerfile.dev .

# This is used to run the test for npm
script:
 - docker run -e CI=true aricahrdson87/frontend npm run test

# Configure the deployment script
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-016876949508"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"